#!/usr/bin/env bash
# PreToolUse hook (matcher: Edit|Write|MultiEdit|NotebookEdit).
#
# Denies hand-edits to files that are GENERATED, never authored: build output, the
# pnpm lockfile, TypeScript build caches, API-surface snapshots, and GraphQL codegen
# output. Editing these by hand drifts them from their source of truth and gets
# overwritten on the next regenerate. We point the author at the regen command and
# block the edit (exit 2 → Claude sees the stderr reason and does not run the tool).

set -uo pipefail

input=$(cat)

file=$(printf '%s' "$input" | jq -r '.tool_input.file_path // .tool_input.filePath // empty' 2>/dev/null)
[ -z "$file" ] && exit 0

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
# Repo-relative path (leaves already-relative paths untouched).
rel=${file#"$repo_root"/}

deny() {
  printf 'Blocked: %s\n%s\n' "$rel" "$1" >&2
  exit 2
}

case "$rel" in
  pnpm-lock.yaml)
    deny "The lockfile is generated. Change the relevant package.json, then run 'pnpm install' to regenerate it." ;;
  *.tsbuildinfo)
    deny "TypeScript build cache — regenerated by 'pnpm check-types' / 'pnpm build'. Delete, don't edit." ;;
esac

# API-surface snapshots: packages/<pkg>/etc/<pkg>.api.md
case "$rel" in
  */etc/*.api.md | etc/*.api.md)
    deny "API-surface snapshot generated by API Extractor. Change the package's public API, then run 'pnpm api-check' to regenerate it (and add a changeset). See AGENTS.md → 'Versioning a public-API change'." ;;
esac

# GraphQL codegen output (committed, regenerated only when the schema changes).
case "$rel" in
  packages/query/src/gql-generated.ts | packages/query/src/schema-input-fields.generated.ts | *.generated.ts)
    deny "Generated by GraphQL Codegen. Regenerate with 'pnpm --filter @oc-mui/query codegen' (no backend needed — reads the committed src/schema.graphql). See packages/query/README.md → 'Code generation'." ;;
esac

# Build output directories (match a /dir/ segment anywhere in the path).
case "/$rel/" in
  */dist/* | */dist-types/* | */target/* | */.turbo/* | */playwright-report/*)
    deny "Build output — edit the source and rebuild with 'pnpm build'." ;;
esac

exit 0
