/**
 * FragmentRegistry Service
 *
 * Manages GraphQL fragments registered by community plugins.
 * Enables plugins to extend core GraphQL queries without modifying core code.
 *
 * Usage:
 * 1. Plugins export __injected_fragments__ (auto-generated by fragment-extractor from .graphql files)
 * 2. RemoteLoader calls fragmentRegistry.registerAll() when loading a plugin
 * 3. Core query fetcher (packages/query) injects getMergedFragment("Event") into requests so
 *    Event queries automatically include all registered plugin fields.
 *
 * @example
 * // In a community plugin (e.g. src/graphql/event-fields.graphql)
 * fragment QuizEventFields on Event { quizInfo { hasQuiz } quiz { id title } }
 *
 * // After load, core GetMyEvents / EventsFromSeries / etc. responses include quizInfo and quiz.
 */

import { logger } from "@oc-mui/utils";

const log = logger.child({ component: "FragmentRegistry" });

export interface RegisteredFragment {
  /** The GraphQL type this fragment extends (e.g., "Event", "Series") */
  targetType: string;
  /** The fragment name */
  fragmentName: string;
  /** The raw GraphQL fragment content */
  content: string;
  /** The plugin that registered this fragment */
  pluginId?: string;
}

/**
 * FragmentRegistry - Singleton service for managing GraphQL fragments
 */
class FragmentRegistryService {
  /** Map of target type to array of fragments */
  private fragmentsByType: Map<string, RegisteredFragment[]> = new Map();

  /** All registered fragments */
  private allFragments: RegisteredFragment[] = [];

  /**
   * Register a single fragment
   *
   * @param fragment - The fragment to register
   * @param pluginId - Optional ID of the plugin registering this fragment
   */
  register(fragment: Omit<RegisteredFragment, "pluginId">, pluginId?: string): void {
    const registeredFragment: RegisteredFragment = {
      ...fragment,
      ...(pluginId !== undefined && { pluginId }),
    };

    // Add to all fragments list
    this.allFragments.push(registeredFragment);

    // Add to type-specific map
    const existing = this.fragmentsByType.get(fragment.targetType) || [];
    this.fragmentsByType.set(fragment.targetType, [...existing, registeredFragment]);

    log.debug(
      `registered fragment "${fragment.fragmentName}" for type "${fragment.targetType}"` +
        (pluginId ? ` from plugin "${pluginId}"` : ""),
    );
  }

  /**
   * Register multiple fragments at once (typically from __injected_fragments__)
   *
   * @param fragments - Array of fragments to register
   * @param pluginId - Optional ID of the plugin registering these fragments
   */
  registerAll(
    fragments: Array<Omit<RegisteredFragment, "pluginId">>,
    pluginId?: string,
  ): void {
    for (const fragment of fragments) {
      this.register(fragment, pluginId);
    }
  }

  /**
   * Get all fragments registered for a specific GraphQL type
   *
   * @param targetType - The GraphQL type name (e.g., "Event")
   * @returns Array of fragments for this type
   */
  getFragmentsForType(targetType: string): RegisteredFragment[] {
    return this.fragmentsByType.get(targetType) || [];
  }

  /**
   * Get a merged fragment string for a specific type
   * Combines all registered fragments into one
   *
   * @param targetType - The GraphQL type name
   * @param placeholderName - Name for the combined fragment (default: "PluginFields")
   * @returns Combined GraphQL fragment string or empty fragment if none registered
   */
  getMergedFragment(targetType: string, placeholderName = "PluginFields"): string {
    const fragments = this.getFragmentsForType(targetType);

    if (fragments.length === 0) {
      // Return an empty fragment that just selects the ID (required for valid GraphQL)
      return `fragment ${placeholderName} on ${targetType} { __typename }`;
    }

    // Extract field selections from each fragment and merge them
    const fieldSelections: string[] = [];

    for (const fragment of fragments) {
      // Extract the fields from the fragment content
      // This is a simple extraction - more complex parsing might be needed for nested fields
      const match = fragment.content.match(/fragment\s+\w+\s+on\s+\w+\s*\{([^}]+)\}/s);
      if (match && match[1]) {
        fieldSelections.push(match[1].trim());
      }
    }

    if (fieldSelections.length === 0) {
      return `fragment ${placeholderName} on ${targetType} { __typename }`;
    }

    // Combine all field selections into one fragment
    return `fragment ${placeholderName} on ${targetType} {\n  ${fieldSelections.join("\n  ")}\n}`;
  }

  /**
   * Get all registered fragments
   *
   * @returns Array of all registered fragments
   */
  getAllFragments(): RegisteredFragment[] {
    return [...this.allFragments];
  }

  /**
   * Get all target types that have registered fragments
   *
   * @returns Array of type names
   */
  getRegisteredTypes(): string[] {
    return Array.from(this.fragmentsByType.keys());
  }

  /**
   * Check if a type has any registered fragments
   *
   * @param targetType - The GraphQL type name
   * @returns true if fragments exist for this type
   */
  hasFragmentsForType(targetType: string): boolean {
    const fragments = this.fragmentsByType.get(targetType);
    return fragments !== undefined && fragments.length > 0;
  }

  /**
   * Remove all fragments registered by a specific plugin
   *
   * @param pluginId - The plugin ID to remove fragments for
   */
  unregisterPlugin(pluginId: string): void {
    // Remove from allFragments
    this.allFragments = this.allFragments.filter((f) => f.pluginId !== pluginId);

    // Remove from type-specific maps
    for (const [type, fragments] of this.fragmentsByType.entries()) {
      const filtered = fragments.filter((f) => f.pluginId !== pluginId);
      if (filtered.length === 0) {
        this.fragmentsByType.delete(type);
      } else {
        this.fragmentsByType.set(type, filtered);
      }
    }

    log.debug(`unregistered all fragments from plugin "${pluginId}"`);
  }

  /**
   * Clear all registered fragments
   * Useful for testing or full reset
   */
  clear(): void {
    this.fragmentsByType.clear();
    this.allFragments = [];
    log.debug("cleared all fragments");
  }

  /**
   * Get debug information about the registry
   */
  getDebugInfo(): {
    totalFragments: number;
    fragmentsByType: Record<string, number>;
    plugins: string[];
  } {
    const fragmentsByType: Record<string, number> = {};
    for (const [type, fragments] of this.fragmentsByType.entries()) {
      fragmentsByType[type] = fragments.length;
    }

    const plugins = [...new Set(this.allFragments.map((f) => f.pluginId).filter(Boolean))] as string[];

    return {
      totalFragments: this.allFragments.length,
      fragmentsByType,
      plugins,
    };
  }
}

/**
 * Singleton instance of the FragmentRegistry
 */
export const fragmentRegistry = new FragmentRegistryService();

/**
 * Export the class for testing purposes
 */
export { FragmentRegistryService };

export default fragmentRegistry;
